import type { ThemeDef } from '../types/greeting';

export const THEMES: ThemeDef[] = [
  {
    id: 'rose-garden',
    name: 'Rose Garden',
    occasion: 'birthday',
    palette: 'Blush + Dusty Rose',
    vibe: 'Romantic, soft',
    backgroundColor: 'var(--color-cream)',
    accentColor: 'var(--color-dusty-rose)',
    primaryFont: 'serif',
  },
  {
    id: 'golden-hour',
    name: 'Golden Hour',
    occasion: 'anniversary',
    palette: 'Warm gold + cream',
    vibe: 'Elegant, warm',
    backgroundColor: 'var(--color-cream)',
    accentColor: '#D4AF37',
    primaryFont: 'serif',
  },
  {
    id: 'midnight-bloom',
    name: 'Midnight Bloom',
    occasion: 'any',
    palette: 'Deep navy + lavender',
    vibe: 'Dreamy, mysterious',
    backgroundColor: '#1E1E2A',
    accentColor: 'var(--color-lavender)',
    primaryFont: 'minimal',
  },
  {
    id: 'spring-petals',
    name: 'Spring Petals',
    occasion: 'birthday',
    palette: 'Mint + peach',
    vibe: 'Fresh, cheerful',
    backgroundColor: '#F5FFF9',
    accentColor: '#FFC8A2',
    primaryFont: 'serif',
  },
  {
    id: 'minimal-ink',
    name: 'Minimal Ink',
    occasion: 'congratulations',
    palette: 'Off-white + black',
    vibe: 'Clean, modern',
    backgroundColor: 'var(--color-soft-white)',
    accentColor: 'var(--color-ink)',
    primaryFont: 'minimal',
  },
  {
    id: 'celestial',
    name: 'Celestial',
    occasion: 'any',
    palette: 'Soft purple + stars',
    vibe: 'Magical, ethereal',
    backgroundColor: '#F3EFFF',
    accentColor: '#B69CEB',
    primaryFont: 'script',
  },
  {
    id: 'pixel-arcade',
    name: 'Pixel Arcade',
    occasion: 'custom',
    palette: 'Deep purple + neon',
    vibe: 'Retro, vibrant',
    backgroundColor: '#2E1065',
    accentColor: '#34D399',
    primaryFont: 'minimal',
  }
];
